Fix JWT authentication when loading exercise templates
apluslms/radar pull request #40
Opened 2022-12-08 19:18 UTC by PasiSa

The permission attributes were missing from JWT token sent to Gitmanager. Fixes #37.

# Description

**What?**

As discussed in the issue description. Will do the needed aplus-auth config changes to run-radar docker setup separately.

**Why?**

[ANSWER HERE]

**How?**

[ANSWER HERE]

Fixes #<issue number>

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [ ] Manual testing.

[ADD A DESCRIPTION ABOUT WHAT YOU TESTED MANUALLY]

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2022-12-13 13:47 UTC, Mankro requested changes
This looks great! I just think you forgot two function calls when you modified the parameters in the function definitions. Python crashes when the function call does not include all mandatory positional parameters.

2022-12-13 13:47 UTC, Mankro commented on provider/aplus.py
> +def load_exercise_template_from_api_data(exercise_data, course):
Below, in the function `load_exercise_template()`, this function `load_exercise_template_from_api_data()` is called, but you have not updated the parameters in the call. Doesn't that cause a crash in `load_exercise_template()`? Please check this.

I guess `load_exercise_template()` already has easy access to the `course` object via `exercise.course` there.

2022-12-13 13:47 UTC, Mankro commented on provider/aplus.py
> +def get_radar_config(exercise_data, course):
In the function `provider.tasks.create_submission()`, this function `get_radar_config()` is called, but you have not updated the parameters in the call. The function already contains a `course` variable so adding it to the function call should be easy.

2022-12-15 19:54 UTC, PasiSa commented
> This looks great! I just think you forgot two function calls when you modified the parameters in the function definitions. Python crashes when the function call does not include all mandatory positional parameters.

Fixed as suggested (and tested too, believe it or not :-)

2022-12-16 17:10 UTC, merged